version: "3"
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=welcome
    ports:
      - "3306:3306"
    volumes:
      - ./order/internal/infrastructure/repository/migrations/init.sql:/docker-entrypoint-initdb.d/init_order.sql
      - ./payment/internal/infrastructure/repository/migrations/init.sql:/docker-entrypoint-initdb.d/init_payment.sql
