version: "3"

services:
  payment:
    depends_on:
      mysql:
        condition: service_healthy
    build: ../payment/
    environment:
      APPLICATION_PORT: 8081
      ENV: "development"
      DATA_SOURCE_URL: "root:welcome@tcp(mysql:3306)/payments?parseTime=True"
  order:
    depends_on:
      mysql:
        condition: service_healthy
    build: ../order/
    ports:
      - "8080:8080"
    environment:
      APPLICATION_PORT: 8080
      ENV: "development"
      DATA_SOURCE_URL: "root:welcome@tcp(mysql:3306)/orders?parseTime=True"
      PAYMENT_SERVICE_URL: "payment:8081"
  mysql:
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: "welcome"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pwelcome"]
      interval: 5s
      timeout: 5s
      retries: 20
