// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/peppydays/grpc-in-go-service/microservices/order/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// PlaceOrder provides a mock function with given fields: order
func (_m *OrderService) PlaceOrder(order domain.Order) (domain.Order, error) {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Order) (domain.Order, error)); ok {
		return rf(order)
	}
	if rf, ok := ret.Get(0).(func(domain.Order) domain.Order); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}

	if rf, ok := ret.Get(1).(func(domain.Order) error); ok {
		r1 = rf(order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
