name: "Execute Listing"

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_EMAIL: "${{ github.actor }}@users.noreply.github.com"

on:
  workflow_dispatch:
    inputs:
      listing:
        type: string
        description: "Listing number (e.g. 2.1)"
        required: true

jobs:
  execute-listing:
    name: "Executing listing ${{ github.event.inputs.listing }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - run: |
          sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - run: |
          cd "$(find . -name listing_${{ github.event.inputs.listing }})"
          ./run.sh ${{ env.GITHUB_USERNAME }} ${{ env.GITHUB_EMAIL }}
